package com.certification.exceptions_and_assertions;

/* 1.Resources are closed after the try clause ends and before any catch/finally clauses.
*  2.Resources are closed in the reverse order from which they were created.
*
* */
public class ExceptionsPuttingAllTogether {

    public static void main(String[] args) {


    }
}
